# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [1]:
# Import pandas using the standard alias
import pandas as pd

In [2]:
# Import the file via read_csv
df = pd.read_csv('Data\Zipcode_Demos.csv', skiprows=1)
#Print a summary of the DataFrame
print(df.info())

print("\n")

print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 47 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            56 non-null     int64
 1   Unnamed: 1   56 non-null     object
 2   0            56 non-null     object
 3   Unnamed: 3   11 non-null     object
 4   Unnamed: 4   11 non-null     object
 5   Unnamed: 5   11 non-null     object
 6   Unnamed: 6   11 non-null     object
 7   Unnamed: 7   11 non-null     object
 8   Unnamed: 8   11 non-null     object
 9   Unnamed: 9   11 non-null     object
 10  Unnamed: 10  11 non-null     object
 11  Unnamed: 11  11 non-null     object
 12  Unnamed: 12  11 non-null     object
 13  Unnamed: 13  11 non-null     object
 14  Unnamed: 14  11 non-null     object
 15  Unnamed: 15  11 non-null     object
 16  Unnamed: 16  11 non-null     object
 17  Unnamed: 17  11 non-null     object
 18  Unnamed: 18  11 non-null     object
 19  Unnamed: 19  11 non-null     object
 20  Unnamed: 20  11 non-null     object
 21  Unnamed: 21  11 non-null     object
 22  Unnamed: 22  11 non-null     object
 23  Unnamed: 23  11 non-null     object
 24  Unnamed: 24  11 non-null     object
 25  Unnamed: 25  11 non-null     object
 26  Unnamed: 26  11 non-null     object
 27  Unnamed: 27  11 non-null     object
 28  Unnamed: 28  11 non-null     object
 29  Unnamed: 29  11 non-null     object
 30  Unnamed: 30  11 non-null     object
 31  Unnamed: 31  11 non-null     object
 32  Unnamed: 32  11 non-null     object
 33  Unnamed: 33  11 non-null     object
 34  Unnamed: 34  11 non-null     object
 35  Unnamed: 35  11 non-null     object
 36  Unnamed: 36  11 non-null     object
 37  Unnamed: 37  11 non-null     object
 38  Unnamed: 38  11 non-null     object
 39  Unnamed: 39  11 non-null     object
 40  Unnamed: 40  11 non-null     object
 41  Unnamed: 41  11 non-null     object
 42  Unnamed: 42  11 non-null     object
 43  Unnamed: 43  11 non-null     object
 44  Unnamed: 44  11 non-null     object
 45  Unnamed: 45  11 non-null     object
 46  Unnamed: 46  11 non-null     object
dtypes: int64(1), object(46)
memory usage: 20.7+ KB
None


Index(['1', 'Unnamed: 1', '0', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')

In [3]:
df.head()

,1,Unnamed: 1,0,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Print the last 5 rows of df
df.tail(15)

,1,Unnamed: 1,0,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
41,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
46,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
47,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
48,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
49,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
51,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
52,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
53,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
54,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

# What is going on with this data set? Anything unusual?
The data set contains 57 rows and 47 columns. All columns are unnamed except column 2, contains the average statistics data names, whose values are given in column 3, which is unnamed.

On all the other columns, data is missing except 11 rows per column. We have to do away or drop all the empty columns. 11 rows are what is relevant. Index 0 is metadata and can be droped so that we have readable data.

In [5]:
# Clean up the dataset
df1= df.dropna(axis=0).dropna(axis=1)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 45 to 55
Data columns (total 47 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            11 non-null     int64
 1   Unnamed: 1   11 non-null     object
 2   0            11 non-null     object
 3   Unnamed: 3   11 non-null     object
 4   Unnamed: 4   11 non-null     object
 5   Unnamed: 5   11 non-null     object
 6   Unnamed: 6   11 non-null     object
 7   Unnamed: 7   11 non-null     object
 8   Unnamed: 8   11 non-null     object
 9   Unnamed: 9   11 non-null     object
 10  Unnamed: 10  11 non-null     object
 11  Unnamed: 11  11 non-null     object
 12  Unnamed: 12  11 non-null     object
 13  Unnamed: 13  11 non-null     object
 14  Unnamed: 14  11 non-null     object
 15  Unnamed: 15  11 non-null     object
 16  Unnamed: 16  11 non-null     object
 17  Unnamed: 17  11 non-null     object
 18  Unnamed: 18  11 non-null     object
 19  Unnamed: 19  11 non-null     object
 20  Unnamed: 20  11 non-null     object
 21  Unnamed: 21  11 non-null     object
 22  Unnamed: 22  11 non-null     object
 23  Unnamed: 23  11 non-null     object
 24  Unnamed: 24  11 non-null     object
 25  Unnamed: 25  11 non-null     object
 26  Unnamed: 26  11 non-null     object
 27  Unnamed: 27  11 non-null     object
 28  Unnamed: 28  11 non-null     object
 29  Unnamed: 29  11 non-null     object
 30  Unnamed: 30  11 non-null     object
 31  Unnamed: 31  11 non-null     object
 32  Unnamed: 32  11 non-null     object
 33  Unnamed: 33  11 non-null     object
 34  Unnamed: 34  11 non-null     object
 35  Unnamed: 35  11 non-null     object
 36  Unnamed: 36  11 non-null     object
 37  Unnamed: 37  11 non-null     object
 38  Unnamed: 38  11 non-null     object
 39  Unnamed: 39  11 non-null     object
 40  Unnamed: 40  11 non-null     object
 41  Unnamed: 41  11 non-null     object
 42  Unnamed: 42  11 non-null     object
 43  Unnamed: 43  11 non-null     object
 44  Unnamed: 44  11 non-null     object
 45  Unnamed: 45  11 non-null     object
 46  Unnamed: 46  11 non-null     object
dtypes: int64(1), object(46)
memory usage: 4.1+ KB

In [6]:
print(df1)

     1         Unnamed: 1                   0    Unnamed: 3      Unnamed: 4  \
45  47  JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE  PERCENT FEMALE
46  48              10001                  44            22             0.5
47  49              10002                  35            19            0.54
48  50              10003                   1             1               1
49  51              10004                   0             0               0
50  52              10005                   2             2               1
51  53              10006                   6             2            0.33
52  54              10007                   1             0               0
53  55              10009                   2             0               0
54  56              10010                   0             0               0
55  57              10011                   3             2            0.67

    Unnamed: 5    Unnamed: 6            Unnamed: 7              Unnamed: 8  \
45  COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN  PERCENT GENDER UNKNOWN
46          22           0.5                     0                       0
47          16          0.46                     0                       0
48           0             0                     0                       0
49           0             0                     0                       0
50           0             0                     0                       0
51           4          0.67                     0                       0
52           1             1                     0                       0
53           2             1                     0                       0
54           0             0                     0                       0
55           1          0.33                     0                       0

            Unnamed: 9  ...                 Unnamed: 37  \
45  COUNT GENDER TOTAL  ...  COUNT CITIZEN STATUS TOTAL
46                  44  ...                          44
47                  35  ...                          35
48                   1  ...                           1
49                   0  ...                           0
50                   2  ...                           2
51                   6  ...                           6
52                   1  ...                           1
53                   2  ...                           2
54                   0  ...                           0
55                   3  ...                           3

                     Unnamed: 38                       Unnamed: 39  \
45  PERCENT CITIZEN STATUS TOTAL  COUNT RECEIVES PUBLIC ASSISTANCE
46                           100                                20
47                           100                                 2
48                           100                                 0
49                             0                                 0
50                           100                                 0
51                           100                                 0
52                           100                                 1
53                           100                                 0
54                             0                                 0
55                           100                                 0

                           Unnamed: 40                        Unnamed: 41  \
45  PERCENT RECEIVES PUBLIC ASSISTANCE  COUNT NRECEIVES PUBLIC ASSISTANCE
46                                0.45                                 24
47                                0.06                                 33
48                                   0                                  1
49                                   0                                  0
50                                   0                                  2
51                                   0                                  6
52                                   1                                  0
53                                   0                                  2
54                                   0                                  0
55                                   0                                  3

                            Unnamed: 42                      Unnamed: 43  \
45  PERCENT NRECEIVES PUBLIC ASSISTANCE  COUNT PUBLIC ASSISTANCE UNKNOWN
46                                 0.55                                0
47                                 0.94                                0
48                                    1                                0
49                                    0                                0
50                                    1                                0
51                                    1                                0
52                                    0                                0
53                                    1                                0
54                                    0                                0
55                                    1                                0

                          Unnamed: 44                    Unnamed: 45  \
45  PERCENT PUBLIC ASSISTANCE UNKNOWN  COUNT PUBLIC ASSISTANCE TOTAL
46                                  0                             44
47                                  0                             35
48                                  0                              1
49                                  0                              0
50                                  0                              2
51                                  0                              6
52                                  0                              1
53                                  0                              2
54                                  0                              0
55                                  0                              3

                        Unnamed: 46
45  PERCENT PUBLIC ASSISTANCE TOTAL
46                              100
47                              100
48                              100
49                                0
50                              100
51                              100
52                              100
53                              100
54                                0
55                              100

[11 rows x 47 columns]

In [7]:
df1.head(11)

,1,Unnamed: 1,0,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
45,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
46,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
47,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
48,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
49,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
51,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
52,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
53,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
54,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [8]:
df1= df1.reset_index(drop=True)
print(df1.head(11))

     1         Unnamed: 1                   0    Unnamed: 3      Unnamed: 4  \
0   47  JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE  PERCENT FEMALE
1   48              10001                  44            22             0.5
2   49              10002                  35            19            0.54
3   50              10003                   1             1               1
4   51              10004                   0             0               0
5   52              10005                   2             2               1
6   53              10006                   6             2            0.33
7   54              10007                   1             0               0
8   55              10009                   2             0               0
9   56              10010                   0             0               0
10  57              10011                   3             2            0.67

    Unnamed: 5    Unnamed: 6            Unnamed: 7              Unnamed: 8  \
0   COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN  PERCENT GENDER UNKNOWN
1           22           0.5                     0                       0
2           16          0.46                     0                       0
3            0             0                     0                       0
4            0             0                     0                       0
5            0             0                     0                       0
6            4          0.67                     0                       0
7            1             1                     0                       0
8            2             1                     0                       0
9            0             0                     0                       0
10           1          0.33                     0                       0

            Unnamed: 9  ...                 Unnamed: 37  \
0   COUNT GENDER TOTAL  ...  COUNT CITIZEN STATUS TOTAL
1                   44  ...                          44
2                   35  ...                          35
3                    1  ...                           1
4                    0  ...                           0
5                    2  ...                           2
6                    6  ...                           6
7                    1  ...                           1
8                    2  ...                           2
9                    0  ...                           0
10                   3  ...                           3

                     Unnamed: 38                       Unnamed: 39  \
0   PERCENT CITIZEN STATUS TOTAL  COUNT RECEIVES PUBLIC ASSISTANCE
1                            100                                20
2                            100                                 2
3                            100                                 0
4                              0                                 0
5                            100                                 0
6                            100                                 0
7                            100                                 1
8                            100                                 0
9                              0                                 0
10                           100                                 0

                           Unnamed: 40                        Unnamed: 41  \
0   PERCENT RECEIVES PUBLIC ASSISTANCE  COUNT NRECEIVES PUBLIC ASSISTANCE
1                                 0.45                                 24
2                                 0.06                                 33
3                                    0                                  1
4                                    0                                  0
5                                    0                                  2
6                                    0                                  6
7                                    1                                  0
8                                    0                                  2
9                                    0                                  0
10                                   0                                  3

                            Unnamed: 42                      Unnamed: 43  \
0   PERCENT NRECEIVES PUBLIC ASSISTANCE  COUNT PUBLIC ASSISTANCE UNKNOWN
1                                  0.55                                0
2                                  0.94                                0
3                                     1                                0
4                                     0                                0
5                                     1                                0
6                                     1                                0
7                                     0                                0
8                                     1                                0
9                                     0                                0
10                                    1                                0

                          Unnamed: 44                    Unnamed: 45  \
0   PERCENT PUBLIC ASSISTANCE UNKNOWN  COUNT PUBLIC ASSISTANCE TOTAL
1                                   0                             44
2                                   0                             35
3                                   0                              1
4                                   0                              0
5                                   0                              2
6                                   0                              6
7                                   0                              1
8                                   0                              2
9                                   0                              0
10                                  0                              3

                        Unnamed: 46
0   PERCENT PUBLIC ASSISTANCE TOTAL
1                               100
2                               100
3                               100
4                                 0
5                               100
6                               100
7                               100
8                               100
9                                 0
10                              100

[11 rows x 47 columns]

In [9]:
# Drop column 0 from df1
df1 = df1.drop(df1.columns[0], axis=1)

# Display the updated DataFrame
print(df1)

           Unnamed: 1                   0    Unnamed: 3      Unnamed: 4  \
0   JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE  PERCENT FEMALE
1               10001                  44            22             0.5
2               10002                  35            19            0.54
3               10003                   1             1               1
4               10004                   0             0               0
5               10005                   2             2               1
6               10006                   6             2            0.33
7               10007                   1             0               0
8               10009                   2             0               0
9               10010                   0             0               0
10              10011                   3             2            0.67

    Unnamed: 5    Unnamed: 6            Unnamed: 7              Unnamed: 8  \
0   COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN  PERCENT GENDER UNKNOWN
1           22           0.5                     0                       0
2           16          0.46                     0                       0
3            0             0                     0                       0
4            0             0                     0                       0
5            0             0                     0                       0
6            4          0.67                     0                       0
7            1             1                     0                       0
8            2             1                     0                       0
9            0             0                     0                       0
10           1          0.33                     0                       0

            Unnamed: 9           Unnamed: 10  ...                 Unnamed: 37  \
0   COUNT GENDER TOTAL  PERCENT GENDER TOTAL  ...  COUNT CITIZEN STATUS TOTAL
1                   44                   100  ...                          44
2                   35                   100  ...                          35
3                    1                   100  ...                           1
4                    0                     0  ...                           0
5                    2                   100  ...                           2
6                    6                   100  ...                           6
7                    1                   100  ...                           1
8                    2                   100  ...                           2
9                    0                     0  ...                           0
10                   3                   100  ...                           3

                     Unnamed: 38                       Unnamed: 39  \
0   PERCENT CITIZEN STATUS TOTAL  COUNT RECEIVES PUBLIC ASSISTANCE
1                            100                                20
2                            100                                 2
3                            100                                 0
4                              0                                 0
5                            100                                 0
6                            100                                 0
7                            100                                 1
8                            100                                 0
9                              0                                 0
10                           100                                 0

                           Unnamed: 40                        Unnamed: 41  \
0   PERCENT RECEIVES PUBLIC ASSISTANCE  COUNT NRECEIVES PUBLIC ASSISTANCE
1                                 0.45                                 24
2                                 0.06                                 33
3                                    0                                  1
4                                    0                                  0
5                                    0                                  2
6                                    0                                  6
7                                    1                                  0
8                                    0                                  2
9                                    0                                  0
10                                   0                                  3

                            Unnamed: 42                      Unnamed: 43  \
0   PERCENT NRECEIVES PUBLIC ASSISTANCE  COUNT PUBLIC ASSISTANCE UNKNOWN
1                                  0.55                                0
2                                  0.94                                0
3                                     1                                0
4                                     0                                0
5                                     1                                0
6                                     1                                0
7                                     0                                0
8                                     1                                0
9                                     0                                0
10                                    1                                0

                          Unnamed: 44                    Unnamed: 45  \
0   PERCENT PUBLIC ASSISTANCE UNKNOWN  COUNT PUBLIC ASSISTANCE TOTAL
1                                   0                             44
2                                   0                             35
3                                   0                              1
4                                   0                              0
5                                   0                              2
6                                   0                              6
7                                   0                              1
8                                   0                              2
9                                   0                              0
10                                  0                              3

                        Unnamed: 46
0   PERCENT PUBLIC ASSISTANCE TOTAL
1                               100
2                               100
3                               100
4                                 0
5                               100
6                               100
7                               100
8                               100
9                                 0
10                              100

[11 rows x 46 columns]

In [10]:
# Set row 0 as the column headers
df1.columns = df1.iloc[0]

# Drop row 0 from the DataFrame since it's now the header
df1 = df1[1:].reset_index(drop=True)

# Display the updated DataFrame
print(df1)

0 JURISDICTION NAME COUNT PARTICIPANTS COUNT FEMALE PERCENT FEMALE COUNT MALE  \
0             10001                 44           22            0.5         22
1             10002                 35           19           0.54         16
2             10003                  1            1              1          0
3             10004                  0            0              0          0
4             10005                  2            2              1          0
5             10006                  6            2           0.33          4
6             10007                  1            0              0          1
7             10009                  2            0              0          2
8             10010                  0            0              0          0
9             10011                  3            2           0.67          1

0 PERCENT MALE COUNT GENDER UNKNOWN PERCENT GENDER UNKNOWN COUNT GENDER TOTAL  \
0          0.5                    0                      0                 44
1         0.46                    0                      0                 35
2            0                    0                      0                  1
3            0                    0                      0                  0
4            0                    0                      0                  2
5         0.67                    0                      0                  6
6            1                    0                      0                  1
7            1                    0                      0                  2
8            0                    0                      0                  0
9         0.33                    0                      0                  3

0 PERCENT GENDER TOTAL  ... COUNT CITIZEN STATUS TOTAL  \
0                  100  ...                         44
1                  100  ...                         35
2                  100  ...                          1
3                    0  ...                          0
4                  100  ...                          2
5                  100  ...                          6
6                  100  ...                          1
7                  100  ...                          2
8                    0  ...                          0
9                  100  ...                          3

0 PERCENT CITIZEN STATUS TOTAL COUNT RECEIVES PUBLIC ASSISTANCE  \
0                          100                               20
1                          100                                2
2                          100                                0
3                            0                                0
4                          100                                0
5                          100                                0
6                          100                                1
7                          100                                0
8                            0                                0
9                          100                                0

0 PERCENT RECEIVES PUBLIC ASSISTANCE COUNT NRECEIVES PUBLIC ASSISTANCE  \
0                               0.45                                24
1                               0.06                                33
2                                  0                                 1
3                                  0                                 0
4                                  0                                 2
5                                  0                                 6
6                                  1                                 0
7                                  0                                 2
8                                  0                                 0
9                                  0                                 3

0 PERCENT NRECEIVES PUBLIC ASSISTANCE COUNT PUBLIC ASSISTANCE UNKNOWN  \
0                                0.55                               0
1                                0.94                               0
2                                   1                               0
3                                   0                               0
4                                   1                               0
5                                   1                               0
6                                   0                               0
7                                   1                               0
8                                   0                               0
9                                   1                               0

0 PERCENT PUBLIC ASSISTANCE UNKNOWN COUNT PUBLIC ASSISTANCE TOTAL  \
0                                 0                            44
1                                 0                            35
2                                 0                             1
3                                 0                             0
4                                 0                             2
5                                 0                             6
6                                 0                             1
7                                 0                             2
8                                 0                             0
9                                 0                             3

0 PERCENT PUBLIC ASSISTANCE TOTAL
0                             100
1                             100
2                             100
3                               0
4                             100
5                             100
6                             100
7                             100
8                               0
9                             100

[10 rows x 46 columns]

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [13]:
data=pd.read_csv('Data\Yelp_Reviews_Corrupt.csv')

ParserError: Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

In [16]:
# Hint: Here's a useful programming pattern to use
try:
    # Do something
    data = pd.read_csv('Data\Yelp_Reviews_Corrupt.csv')
except Exception as e:
    # Handle your exception e
    print("Oooops! An error occurred while loading the file:", e)

Oooops! An error occurred while loading the file: Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

## Summary

Congratulations, you now practiced your Pandas-importing skills.